imie1 = input("Czesc, jak masz na imie? ")
print("Milo cie poznac, " + imie1)
imie2 = input("Czesc, jak masz na imie? ")
print("Milo cie poznac, " + imie2)
imie3 = input("Czesc, jak masz na imie? ")
print("Milo cie poznac, " + imie3)
